import = [
  "~/.config/alacritty/gruvbox_light.toml"
]

[font]
size = 12.0

[font.bold]
family = "Monaspace Neon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Neon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Neon"
style = "Italic"

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"
mods = "Shift"

[window]
option_as_alt = "OnlyRight"
